#Analisis DAST ESSENTIALS
name: DastEssentials 
on: push
jobs:
  Dast-essentials:
    runs-on: ubuntu-latest
    steps:
    - name: Veracode Action Step DAST
      id: veracode
      uses: veracode/veracode-dast-essentials-action@v1.0.1
      with:
        VERACODE_WEBHOOK: '${{secrets.VERACODE_WEBHOOK}}'
        VERACODE_SECRET_ID: '${{secrets.VERACODE_API_ID}}'
        VERACODE_SECRET_ID_KEY: '${{secrets.VERACODE_API_KEY}}'
        pull-report: 'true'
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v1 
      with:
       report_paths: 'report.xml'
       github_token: ${{ secrets.GITHUB_TOKEN }}
